# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false

ratings:
    - app/**
    - og/src/**/*
     
exclude_paths:
    - og/src/support/illuminate/**/*
    - og/src/support/lib/**/*
    - .phpstorm.meta.php
