<?php namespace PHPSTORM_META {

    /**
     * @package Og
     * @version 0.1.0
     * @author  Greg Truesdell <odd.greg@gmail.com>
     */

    /** @noinspection PhpIllegalArrayKeyTypeInspection */
    /** @noinspection PhpUnusedLocalVariableInspection */
    //@formatter:off
    $STATIC_METHOD_TYPES = [
        app('')            => [
            ''                                  instanceof \Og\Application,
            'app'                               instanceof \Og\Application,
            'collection'                        instanceof \Og\Collection,
            'config'                            instanceof \Og\Config,
            'context'                           instanceof \Og\Context,
            'database'                          instanceof \Og\Database,
            'events'                            instanceof \Og\Events,
            'forge'                             instanceof \Og\Forge,
            'input'                             instanceof \Og\Support\Collections\Input,
            'ioc'                               instanceof \Illuminate\Container\Container,
            'kernel'                            instanceof \Og\Kernel,
            'logger'                            instanceof \Tracy\Firelogger,
            'paths'                             instanceof \Og\Paths,
            'request'                           instanceof \Zend\Stratigility\Http\Request,
            'response'                          instanceof \Zend\Stratigility\Http\Response,
            'routing'                           instanceof \Og\Routing,
            'server'                            instanceof \Zend\Diactoros\Server,
            'session'                           instanceof \Aura\Session\Session,
            'yaml'                              instanceof \Symfony\Component\Yaml\Yaml,
            # classes
            '\Aura\Session\Session'              instanceof Aura\Session\Session,
            '\Illuminate\Container\Container'    instanceof Illuminate\Container\Container,
            '\Og\Application'                    instanceof Og\Application,
            '\Og\Collection'                     instanceof Og\Collection,
            '\Og\Config'                         instanceof Og\Config,
            '\Og\Context'                        instanceof Og\Context,
            '\Og\Database'                       instanceof Og\Database,
            '\Og\Events'                         instanceof Og\Events,
            '\Og\Forge'                          instanceof Og\Forge,
            '\Og\Kernel'                         instanceof Og\Kernel,
            '\Og\Paths'                          instanceof Og\Paths,
            '\Og\Routing'                        instanceof Og\Routing,
            '\Tracy\Firelogger'                  instanceof Tracy\Firelogger,
            '\Symfony\Component\Yaml\Yaml'       instanceof Symfony\Component\Yaml\Yaml,
            '\Zend\Diactoros\Server'             instanceof Zend\Diactoros\Server,
            '\Zend\Stratigility\Http\Request'    instanceof Zend\Stratigility\Http\Request,
            '\Zend\Stratigility\Http\Response'   instanceof Zend\Stratigility\Http\Response,
        ],
        forge('')          => [
            # aliases
            ''                                  instanceof \Og\Forge,
            'app'                               instanceof \Og\Application,
            'collection'                        instanceof \Og\Collection,
            'config'                            instanceof \Og\Config,
            'context'                           instanceof \Og\Context,
            'database'                          instanceof \Og\Database,
            'events'                            instanceof \Og\Events,
            'forge'                             instanceof \Og\Forge,
            'input'                             instanceof \Og\Support\Collections\Input,
            'ioc'                               instanceof \Illuminate\Container\Container,
            'kernel'                            instanceof \Og\Kernel,
            'logger'                            instanceof \Tracy\Firelogger,
            'paths'                             instanceof \Og\Paths,
            'request'                           instanceof \Zend\Stratigility\Http\Request,
            'response'                          instanceof \Zend\Stratigility\Http\Response,
            'routing'                           instanceof \Og\Routing,
            'server'                            instanceof \Zend\Diactoros\Server,
            'session'                           instanceof \Aura\Session\Session,
            'yaml'                              instanceof \Symfony\Component\Yaml\Yaml,
            # classes                                      
            '\Aura\Session\Session'              instanceof \Aura\Session\Session,
            '\Illuminate\Container\Container'    instanceof \Illuminate\Container\Container,
            '\Og\Application'                    instanceof \Og\Application,
            '\Og\Collection'                     instanceof \Og\Collection,
            '\Og\Config'                         instanceof \Og\Config,
            '\Og\Context'                        instanceof \Og\Context,
            '\Og\Database'                       instanceof \Og\Database,
            '\Og\Events'                         instanceof \Og\Events,
            '\Og\Forge'                          instanceof \Og\Forge,
            '\Og\Kernel'                         instanceof \Og\Kernel,
            '\Og\Paths'                          instanceof \Og\Paths,
            '\Og\Routing'                        instanceof \Og\Routing,
            '\Tracy\Firelogger'                  instanceof \Tracy\Firelogger,
            '\Symfony\Component\Yaml\Yaml'       instanceof \Symfony\Component\Yaml\Yaml,
            '\Zend\Diactoros\Server'             instanceof \Zend\Diactoros\Server,
            '\Zend\Stratigility\Http\Request'    instanceof \Zend\Stratigility\Http\Request,
            '\Zend\Stratigility\Http\Response'   instanceof \Zend\Stratigility\Http\Response,
        ],
        \Og\Forge::make('') => [
            # aliases
            '' == '@',
            'app'                               instanceof \Og\Application,
            'collection'                        instanceof \Og\Collection,
            'config'                            instanceof \Og\Config,
            'context'                           instanceof \Og\Context,
            'database'                          instanceof \Og\Database,
            'events'                            instanceof \Og\Events,
            'forge'                             instanceof \Og\Forge,
            'input'                             instanceof \Og\Support\Collections\Input,
            'ioc'                               instanceof \Illuminate\Container\Container,
            'kernel'                            instanceof \Og\Kernel,
            'logger'                            instanceof \Tracy\Firelogger,
            'paths'                             instanceof \Og\Paths,
            'request'                           instanceof \Zend\Stratigility\Http\Request,
            'response'                          instanceof \Zend\Stratigility\Http\Response,
            'routing'                           instanceof \Og\Routing,
            'server'                            instanceof \Zend\Diactoros\Server,
            'session'                           instanceof \Aura\Session\Session,
            'yaml'                              instanceof \Symfony\Component\Yaml\Yaml,
            # classes
            '\Aura\Session\Session'              instanceof \Aura\Session\Session,
            '\Illuminate\Container\Container'    instanceof \Illuminate\Container\Container,
            '\Og\Application'                    instanceof \Og\Application,
            '\Og\Collection'                     instanceof \Og\Collection,
            '\Og\Config'                         instanceof \Og\Config,
            '\Og\Context'                        instanceof \Og\Context,
            '\Og\Database'                       instanceof \Og\Database,
            '\Og\Events'                         instanceof \Og\Events,
            '\Og\Forge'                          instanceof \Og\Forge,
            '\Og\Kernel'                         instanceof \Og\Kernel,
            '\Og\Paths'                          instanceof \Og\Paths,
            '\Og\Routing'                        instanceof \Og\Routing,
            '\Tracy\Firelogger'                  instanceof \Tracy\Firelogger,
            '\Symfony\Component\Yaml\Yaml'       instanceof \Symfony\Component\Yaml\Yaml,
            '\Zend\Diactoros\Server'             instanceof \Zend\Diactoros\Server,
            '\Zend\Stratigility\Http\Request'    instanceof \Zend\Stratigility\Http\Request,
            '\Zend\Stratigility\Http\Response'   instanceof \Zend\Stratigility\Http\Response,
        ],
        new \Og\Forge => [
            # aliases
            '' == '@',
            'app'                               instanceof \Og\Application,
            'collection'                        instanceof \Og\Collection,
            'config'                            instanceof \Og\Config,
            'context'                           instanceof \Og\Context,
            'database'                          instanceof \Og\Database,
            'events'                            instanceof \Og\Events,
            'forge'                             instanceof \Og\Forge,
            'input'                             instanceof \Og\Support\Collections\Input,
            'ioc'                               instanceof \Illuminate\Container\Container,
            'kernel'                            instanceof \Og\Kernel,
            'logger'                            instanceof \Tracy\Firelogger,
            'paths'                             instanceof \Og\Paths,
            'request'                           instanceof \Zend\Stratigility\Http\Request,
            'response'                          instanceof \Zend\Stratigility\Http\Response,
            'routing'                           instanceof \Og\Routing,
            'server'                            instanceof \Zend\Diactoros\Server,
            'session'                           instanceof \Aura\Session\Session,
            'yaml'                              instanceof \Symfony\Component\Yaml\Yaml,
            # classes
            '\Aura\Session\Session'              instanceof \Aura\Session\Session,
            '\Illuminate\Container\Container'    instanceof \Illuminate\Container\Container,
            '\Og\Application'                    instanceof \Og\Application,
            '\Og\Collection'                     instanceof \Og\Collection,
            '\Og\Config'                         instanceof \Og\Config,
            '\Og\Context'                        instanceof \Og\Context,
            '\Og\Database'                       instanceof \Og\Database,
            '\Og\Events'                         instanceof \Og\Events,
            '\Og\Forge'                          instanceof \Og\Forge,
            '\Og\Kernel'                         instanceof \Og\Kernel,
            '\Og\Paths'                          instanceof \Og\Paths,
            '\Og\Routing'                        instanceof \Og\Routing,
            '\Tracy\Firelogger'                  instanceof \Tracy\Firelogger,
            '\Symfony\Component\Yaml\Yaml'       instanceof \Symfony\Component\Yaml\Yaml,
            '\Zend\Diactoros\Server'             instanceof \Zend\Diactoros\Server,
            '\Zend\Stratigility\Http\Request'    instanceof \Zend\Stratigility\Http\Request,
            '\Zend\Stratigility\Http\Response'   instanceof \Zend\Stratigility\Http\Response,
        ],
        \Og\Forge::get('')  => [
            # aliases
            '' == '@',
            'app'                               instanceof \Og\Application,
            'collection'                        instanceof \Og\Collection,
            'config'                            instanceof \Og\Config,
            'context'                           instanceof \Og\Context,
            'database'                          instanceof \Og\Database,
            'events'                            instanceof \Og\Events,
            'forge'                             instanceof \Og\Forge,
            'input'                             instanceof \Og\Support\Collections\Input,
            'ioc'                               instanceof \Illuminate\Container\Container,
            'kernel'                            instanceof \Og\Kernel,
            'logger'                            instanceof \Tracy\Firelogger,
            'paths'                             instanceof \Og\Paths,
            'request'                           instanceof \Zend\Stratigility\Http\Request,
            'response'                          instanceof \Zend\Stratigility\Http\Response,
            'routing'                           instanceof \Og\Routing,
            'server'                            instanceof \Zend\Diactoros\Server,
            'session'                           instanceof \Aura\Session\Session,
            'yaml'                              instanceof \Symfony\Component\Yaml\Yaml,
            # classes
            '\Aura\Session\Session'              instanceof \Aura\Session\Session,
            '\Illuminate\Container\Container'    instanceof \Illuminate\Container\Container,
            '\Og\Application'                    instanceof \Og\Application,
            '\Og\Collection'                     instanceof \Og\Collection,
            '\Og\Config'                         instanceof \Og\Config,
            '\Og\Context'                        instanceof \Og\Context,
            '\Og\Database'                       instanceof \Og\Database,
            '\Og\Events'                         instanceof \Og\Events,
            '\Og\Forge'                          instanceof \Og\Forge,
            '\Og\Kernel'                         instanceof \Og\Kernel,
            '\Og\Paths'                          instanceof \Og\Paths,
            '\Og\Routing'                        instanceof \Og\Routing,
            '\Tracy\Firelogger'                  instanceof \Tracy\Firelogger,
            '\Symfony\Component\Yaml\Yaml'       instanceof \Symfony\Component\Yaml\Yaml,
            '\Zend\Diactoros\Server'             instanceof \Zend\Diactoros\Server,
            '\Zend\Stratigility\Http\Request'    instanceof \Zend\Stratigility\Http\Request,
            '\Zend\Stratigility\Http\Response'   instanceof \Zend\Stratigility\Http\Response,
        ],
    ];
}
