language: php
php:
- 5.6
cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install: 
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_script:
  - php local/bin/coveralls -v
